name: dev-m1nav-app
region: nyc

services:
  - name: web
    github:
      repo: mach-1-int/mach-1-navigator
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: ${APP_URL}

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
